repos:
  - id: /.*/
    workflow: terraform-infracost

workflows:
  terraform-infracost:
    plan:
      steps:
        - env:
            name: INFRACOST_OUTPUT
            command: echo "/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/infracost-output.json"
        - init
        - plan
        - show
        - run: |
            mkdir -p /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM
            infracost breakdown --path=$SHOWFILE --format=json --log-level=info --out-file=$INFRACOST_OUTPUT
        - run: |
            infracost comment github --repo $BASE_REPO_OWNER/$BASE_REPO_NAME --pull-request $PULL_NUM \
              --path $INFRACOST_OUTPUT --github-token $GITHUB_TOKEN --behavior new
            rm -rf /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM
