name: Build-Cron

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        path:
          - 20-vpc-demo
          - 30-alb-demo
          - 50-eks-demo

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.9" # terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_BRUCE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRUCE }}

      - name: Initialize Terraform
        run: |
          cd ./${{ matrix.path }}
          terraform init -input=false

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: |
          cd ./${{ matrix.path }}
          terraform plan -input=false -no-color -out=tfplan && \
          terraform show -no-color tfplan

      # Sed is taking all lines that begin with one or more spaces followed by a `+` or `-`.
      # It stores the amount of spaces in `\1` and the +/- in `\2`.
      # Then replace that portion of the line with `\2\1` (+/- followed by the number of matched spaces).
      - name: Reformat Plan
        # if: steps.plan.outcome == 'success'
        run: |
          cat <<EOF > plan.txt
          ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
          EOF
          sed -E 's/^([[:space:]]+)([-+])/\2\1/g' plan.txt

      - name: Make Message
        # if: steps.plan.outcome == 'success'
        run: |
          PLAN="$(cat plan.txt | grep 'Plan:')" || NOCH="$(cat plan.txt | grep 'No changes.')"
          [ -z "${PLAN}" ] || cat <<EOF > slack_message.json
          {
            "channel": "sandbox",
            "attachments": [{
              "color": "danger",
              "title": "${{ matrix.path }}",
              "text": "${PLAN}"
            }]
          }
          EOF

      - name: Post Slack
        # if: steps.plan.outcome == 'success'
        uses: opspresso/action-slack@master
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          JSON_PATH: slack_message.json
